from .groups_list_keyboard import group_function_keyboard
from .Tuser_keyboard import get_add_tuser_keyboard, get_tuser_keyboard, get_groups_list_to_add_keyboard, \
    get_groups_list_to_rm_keyboard, tuser_callback_datas, add_to_group_datas, rm_from_group_datas
from .main_inline_keyboard import get_main_inline_keyboard
from .inventrization_keyboards import main_inventarization_keyboard, main_inventarization_callback
from .phones_searcher_keyboards import main_phone_searcher_keyboard, phone_searcher_callback
